# Generated by Django 3.1.4 on 2021-11-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field', models.CharField(max_length=30)),
                ('Type_of_question', models.CharField(max_length=35)),
                ('No_of_questions', models.IntegerField()),
                ('Duration', models.DurationField()),
                ('Name_of_competition', models.CharField(max_length=40)),
                ('Last_date', models.DateField()),
                ('Date_of_exam', models.DateField()),
                ('Time_of_exam', models.TimeField()),
            ],
        ),
    ]
