# Generated by Django 3.1.4 on 2021-11-12 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0002_host_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='Created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuestionsTITA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=300)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.host')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsMCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=300)),
                ('Option1', models.CharField(max_length=20)),
                ('Option2', models.CharField(max_length=20)),
                ('Option3', models.CharField(max_length=20)),
                ('Option4', models.CharField(max_length=20)),
                ('correct', models.CharField(max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.host')),
            ],
        ),
        migrations.CreateModel(
            name='Marks_Of_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
