# Generated by Django 3.1.4 on 2021-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20211113_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chek',
        ),
        migrations.RemoveField(
            model_name='host',
            name='Date_of_exam',
        ),
        migrations.RemoveField(
            model_name='host',
            name='Time_of_exam',
        ),
        migrations.AddField(
            model_name='host',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
