# Generated by Django 3.1.4 on 2021-11-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20211113_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='No_of_questions',
            new_name='Marks_per_question',
        ),
    ]
